version: '3.8'
networks:
  guidebook_net:
    name: ${DOCKER_PROJECT_NAME}_network
    driver: bridge

services:
  api: 
    build:
      context: ..
      dockerfile: docker/api/Dockerfile
    ports:
      - ${DOCKER_API_PORT}:8080
  