version: '3.8'
networks:
  guidebook_net:
    name: ${DOCKER_PROJECT_NAME}_network
    driver: bridge

services:
  api: 
    container_name: ${COMPOSE_PROJECT_NAME}_api
    build:
      context: ..
      dockerfile: docker-local/api/Dockerfile
    ports:
      - ${DOCKER_API_PORT}:8080
    volumes:
      - "../api/lambdas/build/lambda-api/:/var/task"
  
  db:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    image: amazon/dynamodb-local:latest
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - "./db:/home/dynamodblocal/data"
    ports:
      - "8000:8000"
    # restart: always
      
  dbadmin: 
    container_name: dynamodb-admin
    image: "aaronshaf/dynamodb-admin"
    depends_on:
      - db
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://db:8000
      - AWS_REGION=eu-central-1
    # restart: always
    